### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by carlgieringer** [trigger-corp/browser-extensions#52]
I see activity in this repo, but the [docs linked from the README](http://legacy-docs.trigger.io/en/v1.4/modules/browser/index.html) have a danger alert: "This documentation is deprecated, and only kept here to support users of browser extension APIs."

**Comment by antoinevg** [comment]
For the background to this project, please see the introductory blog post linked to from the README: 

http://trigger.io/cross-platform-application-development-blog/2013/09/10/introducing-openforge-an-open-source-cross-platform-browser-add-on-framework/

**Comment by maxvyaznikov** [comment]
There is a fork here, that didn't stuck on:
https://github.com/grammarly/browser-extensions
